services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_DATABASE: book_app
      MYSQL_ROOT_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - book-network

  app:
    build: .
    container_name: springboot_app
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    networks:
      - book-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/book_app
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: mypassword
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: mypassword
    depends_on:
      - mysql
    networks:
      - book-network

volumes:
  mysql-data:

networks:
  book-network:
